apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-location
  description: Central registry for all custom scaffolder templates
spec:
  targets:
    - https://github.com/raunakkhatri/backstage-templates/blob/main/python-app/template.yaml
    - https://github.com/raunakkhatri/backstage-templates/blob/main/nodejs-app/template.yaml
