apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: nodejs-template
  title: Node.js Express template
  description: Provisions a minimalistic Express.js application
spec:
  type: service
  owner: development
  path: ./template.yaml
